version: '3.8'

networks:
  dev-net:
    driver: bridge

services:
  messenger-service:
    container_name: messenger-dev
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - 9090:9090
    volumes:
      - .:/app
    networks:
      - dev-net