version: '3.8'

services:
  messenger-service:
    container_name: messenger-dev
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - 9090:9090
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh
    networks:
      - dev-net

networks:
  dev-net:
    driver: bridge