name: Run Tests on Pull Request

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Compile
      run: mvn compile

    - name: Set environment variable DOMAIN
      run: echo "MAILERSEND_DOMAIN=${{ secrets.MAILERSEND_DOMAIN }}" >> $GITHUB_ENV
    
    - name: Set environment variable TOKEN
      run: echo "MAILERSEND_TOKEN=${{ secrets.MAILERSEND_TOKEN }}" >> $GITHUB_ENV

    - name: Run tests
      run: mvn test

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: edgartf3/ab_messenger:latest