name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Compile
      run: mvn compile

    - name: Set environment variable DOMAIN
      run: echo "MAILERSEND_DOMAIN=${{ secrets.MAILERSEND_DOMAIN }}" >> $GITHUB_ENV
    
    - name: Set environment variable TOKEN
      run: echo "MAILERSEND_TOKEN=${{ secrets.MAILERSEND_TOKEN }}" >> $GITHUB_ENV

    - name: Run tests
      run: mvn test
